-- GENERATED FILE — do not edit by hand.
--
-- Regenerate with:  npm run seed:generate
-- Source of truth:  src/lib/mock/retail-products.ts, wholesale-products.ts
--
-- Loads the placeholder catalogue so a fresh database matches what the app
-- renders today. Every statement upserts on the natural key (slug, or
-- product + label), so re-running updates rather than duplicating and the
-- file is safe to apply to a database that already has data.
--
-- The images are data-URI SVG placeholders, carried over verbatim so the
-- storefront looks identical after the switch. They belong in Supabase
-- Storage once real photography exists — a bucket URL in the same column,
-- no schema change needed.

-- ---------------------------------------------------------------------------
-- Promo codes
--
-- The built-ins from src/lib/pricing.ts. They are flagged built_in so the
-- admin panel can deactivate but not delete them, keeping the UI and the
-- server's fallback list in agreement.
-- ---------------------------------------------------------------------------

insert into promo_codes (code, percent, active, built_in) values
  ('GARMENT10', 10, true, true),
  ('WELCOME5', 5, true, true)
on conflict (code) do update set
  percent = excluded.percent,
  built_in = excluded.built_in;

-- ---------------------------------------------------------------------------
-- Retail catalogue (33 products)
-- ---------------------------------------------------------------------------

insert into retail_products (slug, name, brand, category, subcategory, description,
                            images, price, mrp, currency, colors, rating, rating_count, tags) values
  ('floral-anarkali-kurta', 'Floral Printed Anarkali Kurta', 'Vibe & Co.', 'women'::retail_category,
   'Kurtas', 'A flowy floral anarkali kurta in breathable cotton-blend fabric, perfect for festive days and everyday wear alike.',
   array['/placeholders/anarkali-kurta-e11d48.svg', '/placeholders/back-view-be123c.svg']::text[],
   129900, 219900, 'INR', array['Rose', 'Mustard', 'Teal']::text[],
   4.3, 1284, array['bestseller', 'sale']::retail_tag[]),
  ('embroidered-chikankari-kurti', 'Embroidered Chikankari Kurti', 'Loomcraft', 'women'::retail_category,
   'Kurtas', 'Hand-embroidered Lucknowi chikankari work on soft cotton, a wardrobe staple.',
   array['/placeholders/chikankari-kurti-0891b2.svg']::text[],
   149900, 199900, 'INR', array['White', 'Powder Blue']::text[],
   4.5, 789, array['sale']::retail_tag[]),
  ('block-print-cotton-kurta', 'Block Print Cotton Kurta', 'Loomcraft', 'women'::retail_category,
   'Kurtas', 'Hand block-printed cotton kurta with a relaxed straight fit, dyed using traditional techniques.',
   array['/placeholders/block-print-kurta-b45309.svg']::text[],
   109900, 149900, 'INR', array['Indigo', 'Rust']::text[],
   4.1, 312, '{}'::retail_tag[]),
  ('banarasi-silk-saree', 'Banarasi Silk Blend Saree', 'Loomcraft', 'women'::retail_category,
   'Sarees', 'Traditional Banarasi weave with a rich zari border, comes with an unstitched matching blouse piece.',
   array['/placeholders/silk-saree-9d174d.svg']::text[],
   349900, 499900, 'INR', array['Maroon', 'Emerald', 'Navy']::text[],
   4.6, 542, array['new']::retail_tag[]),
  ('chiffon-printed-saree', 'Chiffon Printed Saree', 'Wanderlust', 'women'::retail_category,
   'Sarees', 'Lightweight chiffon saree with an all-over digital print, easy to drape and travel-friendly.',
   array['/placeholders/chiffon-saree-a21caf.svg']::text[],
   189900, 259900, 'INR', array['Fuchsia', 'Sea Green']::text[],
   4, 176, '{}'::retail_tag[]),
  ('embroidered-anarkali-suit-set', 'Embroidered Anarkali Suit Set', 'Vibe & Co.', 'women'::retail_category,
   'Suit Sets', '3-piece anarkali suit set with embroidered dupatta, festive-ready in a rich fabric blend.',
   array['/placeholders/anarkali-suit-set-7c2d92.svg']::text[],
   259900, 349900, 'INR', array['Wine', 'Gold']::text[],
   4.4, 203, array['new']::retail_tag[]),
  ('printed-palazzo-suit-set', 'Printed Palazzo Suit Set', 'Loomcraft', 'women'::retail_category,
   'Suit Sets', 'Comfortable 3-piece kurta, palazzo, and dupatta set in a breathable cotton blend print.',
   array['/placeholders/palazzo-suit-set-0d9488.svg']::text[],
   169900, 229900, 'INR', array['Sea Green', 'Coral']::text[],
   4.2, 288, '{}'::retail_tag[]),
  ('printed-maxi-dress', 'Printed Tiered Maxi Dress', 'Vibe & Co.', 'women'::retail_category,
   'Dresses', 'Breezy tiered maxi dress with an all-over print, perfect for summer outings.',
   array['/placeholders/maxi-dress-db2777.svg']::text[],
   159900, 219900, 'INR', array['Coral', 'Yellow']::text[],
   4.4, 921, array['bestseller', 'sale']::retail_tag[]),
  ('floral-wrap-dress', 'Floral Wrap Midi Dress', 'Wanderlust', 'women'::retail_category,
   'Dresses', 'A flattering wrap-style midi dress with a floral print, cinched at the waist with a tie belt.',
   array['/placeholders/wrap-dress-c2410c.svg']::text[],
   139900, 189900, 'INR', array['Terracotta', 'Navy']::text[],
   4.3, 401, '{}'::retail_tag[]),
  ('denim-shirt-dress', 'Denim Shirt Dress', 'Denim Union', 'women'::retail_category,
   'Dresses', 'Casual button-down denim shirt dress with a belted waist, styles up or down.',
   array['/placeholders/denim-shirt-dress-1e40af.svg']::text[],
   149900, 199900, 'INR', array['Light Wash', 'Dark Wash']::text[],
   4.1, 167, array['new']::retail_tag[]),
  ('ruffle-sleeve-top', 'Ruffle Sleeve Top', 'Wanderlust', 'women'::retail_category,
   'Tops', 'Flowy top with statement ruffle sleeves, pairs easily with jeans or skirts.',
   array['/placeholders/ruffle-top-db2777.svg']::text[],
   79900, 109900, 'INR', array['Blush', 'Black']::text[],
   4, 234, '{}'::retail_tag[]),
  ('satin-cami-top', 'Satin Cami Top', 'Urban Thread', 'women'::retail_category,
   'Tops', 'Silky satin camisole top with adjustable straps, a versatile layering piece.',
   array['/placeholders/satin-cami-701a75.svg']::text[],
   59900, 89900, 'INR', array['Champagne', 'Black', 'Emerald']::text[],
   4.2, 356, array['bestseller']::retail_tag[]),
  ('high-rise-straight-jeans', 'High-Rise Straight Fit Jeans', 'Denim Union', 'women'::retail_category,
   'Jeans', 'Stretchable high-rise denim with a clean straight fit that pairs with everything.',
   array['/placeholders/straight-jeans-1e3a8a.svg']::text[],
   179900, 229900, 'INR', array['Indigo', 'Black']::text[],
   4.1, 876, '{}'::retail_tag[]),
  ('skinny-fit-ankle-jeans', 'Skinny Fit Ankle Length Jeans', 'Denim Union', 'women'::retail_category,
   'Jeans', 'Ankle-length skinny jeans with 4-way stretch for all-day comfort.',
   array['/placeholders/ankle-jeans-312e81.svg']::text[],
   169900, 219900, 'INR', array['Mid Blue', 'Black']::text[],
   4, 298, '{}'::retail_tag[]),
  ('womens-quilted-puffer-jacket', 'Quilted Puffer Jacket', 'Urban Thread', 'women'::retail_category,
   'Jackets', 'Lightweight quilted puffer with a snap-button front, packable for travel.',
   array['/placeholders/puffer-jacket-1f2937.svg']::text[],
   229900, 299900, 'INR', array['Black', 'Olive', 'Dusty Pink']::text[],
   4.3, 145, array['new']::retail_tag[]),
  ('graphic-print-oversized-tee', 'Graphic Print Oversized T-Shirt', 'Streetline', 'men'::retail_category,
   'T-Shirts', 'Heavyweight cotton oversized tee with a bold front graphic print.',
   array['/placeholders/oversized-tee-0f172a.svg']::text[],
   69900, 99900, 'INR', array['Black', 'White', 'Sage']::text[],
   4.4, 2103, array['bestseller']::retail_tag[]),
  ('classic-crew-neck-tee', 'Classic Crew Neck T-Shirt', 'Urban Thread', 'men'::retail_category,
   'T-Shirts', 'Everyday essential crew neck tee in soft combed cotton, available in core colours.',
   array['/placeholders/crew-neck-tee-334155.svg']::text[],
   49900, 69900, 'INR', array['White', 'Black', 'Grey Melange', 'Navy']::text[],
   4.2, 1567, array['bestseller']::retail_tag[]),
  ('striped-polo-tshirt', 'Striped Polo T-Shirt', 'Oakridge', 'men'::retail_category,
   'T-Shirts', 'Pique cotton polo with a classic stripe pattern, smart-casual essential.',
   array['/placeholders/polo-tee-166534.svg']::text[],
   89900, 119900, 'INR', array['Green Stripe', 'Navy Stripe']::text[],
   4, 245, '{}'::retail_tag[]),
  ('classic-fit-formal-shirt', 'Classic Fit Formal Shirt', 'Oakridge', 'men'::retail_category,
   'Shirts', 'Crisp cotton formal shirt with a classic collar, ideal for office and formal occasions.',
   array['/placeholders/formal-shirt-334155.svg']::text[],
   99900, 149900, 'INR', array['Sky Blue', 'White', 'Charcoal']::text[],
   4.2, 654, '{}'::retail_tag[]),
  ('checked-casual-shirt', 'Checked Casual Shirt', 'Streetline', 'men'::retail_category,
   'Shirts', 'Relaxed-fit checked shirt in brushed cotton, perfect for weekend wear.',
   array['/placeholders/checked-shirt-7f1d1d.svg']::text[],
   84900, 119900, 'INR', array['Red Check', 'Blue Check']::text[],
   4.1, 389, '{}'::retail_tag[]),
  ('mens-slim-fit-jeans', 'Slim Fit Jeans', 'Denim Union', 'men'::retail_category,
   'Jeans', 'Stretch denim slim fit jeans with a mid-rise waist, five-pocket styling.',
   array['/placeholders/slim-jeans-1e3a8a.svg']::text[],
   159900, 209900, 'INR', array['Indigo', 'Black', 'Grey']::text[],
   4.1, 612, array['bestseller']::retail_tag[]),
  ('slim-fit-chino-trousers', 'Slim Fit Chino Trousers', 'Oakridge', 'men'::retail_category,
   'Trousers', 'Wrinkle-resistant slim fit chinos that go from desk to dinner.',
   array['/placeholders/chino-trousers-78350f.svg']::text[],
   149900, 189900, 'INR', array['Khaki', 'Navy', 'Black']::text[],
   4, 321, '{}'::retail_tag[]),
  ('formal-pleated-trousers', 'Formal Pleated Trousers', 'Oakridge', 'men'::retail_category,
   'Trousers', 'Tailored pleated-front formal trousers with a comfortable regular fit.',
   array['/placeholders/pleated-trousers-44403c.svg']::text[],
   139900, 179900, 'INR', array['Charcoal', 'Navy']::text[],
   3.9, 154, '{}'::retail_tag[]),
  ('nehru-jacket-set', 'Nehru Jacket & Kurta Set', 'Vibe & Co.', 'men'::retail_category,
   'Ethnic Wear', 'Festive-ready kurta paired with a contrast Nehru jacket, fully stitched set.',
   array['/placeholders/nehru-jacket-set-065f46.svg']::text[],
   249900, 349900, 'INR', array['Beige', 'Maroon']::text[],
   4.5, 198, array['new']::retail_tag[]),
  ('quilted-bomber-jacket', 'Quilted Bomber Jacket', 'Streetline', 'men'::retail_category,
   'Jackets', 'Lightweight quilted bomber with ribbed cuffs, built for transitional weather.',
   array['/placeholders/bomber-jacket-111827.svg']::text[],
   219900, 279900, 'INR', array['Black', 'Olive']::text[],
   4.2, 156, array['new']::retail_tag[]),
  ('mens-denim-jacket', 'Classic Denim Jacket', 'Denim Union', 'men'::retail_category,
   'Jackets', 'Timeless denim trucker jacket in a mid-wash finish, layers over anything.',
   array['/placeholders/denim-jacket-1e40af.svg']::text[],
   189900, 249900, 'INR', array['Mid Wash', 'Black Wash']::text[],
   4.2, 267, '{}'::retail_tag[]),
  ('unicorn-print-frock', 'Unicorn Print Party Frock', 'Little Vibes', 'kids'::retail_category,
   'Dresses', 'Twirl-worthy party frock with a sparkly unicorn print and soft tulle layer.',
   array['/placeholders/party-frock-c026d3.svg']::text[],
   89900, 129900, 'INR', array['Pink', 'Lilac']::text[],
   4.7, 432, array['bestseller']::retail_tag[]),
  ('floral-cotton-frock', 'Floral Cotton Frock', 'Little Vibes', 'kids'::retail_category,
   'Dresses', 'Everyday cotton frock with a cheerful floral print and comfortable elastic waist.',
   array['/placeholders/cotton-frock-db2777.svg']::text[],
   59900, 84900, 'INR', array['Yellow Floral', 'Blue Floral']::text[],
   4.3, 198, '{}'::retail_tag[]),
  ('girls-lehenga-choli-set', 'Girls Lehenga Choli Set', 'Little Vibes', 'kids'::retail_category,
   'Ethnic Wear', 'Festive lehenga choli set with dupatta, sequin detailing for celebrations.',
   array['/placeholders/lehenga-choli-a21caf.svg']::text[],
   129900, 179900, 'INR', array['Pink Gold', 'Red Gold']::text[],
   4.5, 121, array['new']::retail_tag[]),
  ('boys-printed-tshirt', 'Boys Printed T-Shirt', 'Little Vibes', 'kids'::retail_category,
   'T-Shirts', 'Fun printed cotton tee for everyday play, pre-shrunk and colourfast.',
   array['/placeholders/boys-printed-tee-0369a1.svg']::text[],
   39900, 59900, 'INR', array['Blue', 'Green']::text[],
   4.2, 267, '{}'::retail_tag[]),
  ('boys-solid-polo', 'Boys Solid Polo T-Shirt', 'Oakridge', 'kids'::retail_category,
   'T-Shirts', 'Smart-casual pique polo for boys, great for school events and outings.',
   array['/placeholders/boys-polo-15803d.svg']::text[],
   49900, 69900, 'INR', array['Navy', 'Maroon']::text[],
   4, 143, '{}'::retail_tag[]),
  ('dino-print-tee-shorts-set', 'Dino Print Tee & Shorts Set', 'Little Vibes', 'kids'::retail_category,
   'Co-ord Sets', 'Everyday cotton tee and shorts co-ord set with a playful dinosaur print.',
   array['/placeholders/dino-co-ord-set-15803d.svg']::text[],
   59900, 79900, 'INR', array['Green', 'Blue']::text[],
   4.3, 267, '{}'::retail_tag[]),
  ('girls-floral-coord-set', 'Girls Floral Co-ord Set', 'Little Vibes', 'kids'::retail_category,
   'Co-ord Sets', 'Matching top and skirt co-ord set in a soft floral print, comfy everyday cotton.',
   array['/placeholders/girls-co-ord-set-db2777.svg']::text[],
   64900, 89900, 'INR', array['Pink', 'Peach']::text[],
   4.4, 176, array['new']::retail_tag[])
on conflict (slug) do update set
  name = excluded.name,
  brand = excluded.brand,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  images = excluded.images,
  price = excluded.price,
  mrp = excluded.mrp,
  colors = excluded.colors,
  rating = excluded.rating,
  rating_count = excluded.rating_count,
  tags = excluded.tags,
  is_active = true;

-- Sizes and their stock levels. Quantities come from getStock() in
-- src/lib/stores/stock-store.ts, so the database starts out agreeing with
-- what the storefront currently displays.

insert into retail_product_sizes (product_id, label, stock_qty) values
  ((select id from retail_products where slug = 'floral-anarkali-kurta'), 'S', 16),
  ((select id from retail_products where slug = 'floral-anarkali-kurta'), 'M', 30),
  ((select id from retail_products where slug = 'floral-anarkali-kurta'), 'L', 2),
  ((select id from retail_products where slug = 'floral-anarkali-kurta'), 'XL', 0),
  ((select id from retail_products where slug = 'embroidered-chikankari-kurti'), 'S', 24),
  ((select id from retail_products where slug = 'embroidered-chikankari-kurti'), 'M', 18),
  ((select id from retail_products where slug = 'embroidered-chikankari-kurti'), 'L', 1),
  ((select id from retail_products where slug = 'embroidered-chikankari-kurti'), 'XL', 0),
  ((select id from retail_products where slug = 'block-print-cotton-kurta'), 'S', 27),
  ((select id from retail_products where slug = 'block-print-cotton-kurta'), 'M', 21),
  ((select id from retail_products where slug = 'block-print-cotton-kurta'), 'L', 3),
  ((select id from retail_products where slug = 'block-print-cotton-kurta'), 'XL', 0),
  ((select id from retail_products where slug = 'banarasi-silk-saree'), 'Free Size', 23),
  ((select id from retail_products where slug = 'chiffon-printed-saree'), 'Free Size', 14),
  ((select id from retail_products where slug = 'embroidered-anarkali-suit-set'), 'S', 2),
  ((select id from retail_products where slug = 'embroidered-anarkali-suit-set'), 'M', 1),
  ((select id from retail_products where slug = 'embroidered-anarkali-suit-set'), 'L', 22),
  ((select id from retail_products where slug = 'embroidered-anarkali-suit-set'), 'XL', 0),
  ((select id from retail_products where slug = 'printed-palazzo-suit-set'), 'S', 30),
  ((select id from retail_products where slug = 'printed-palazzo-suit-set'), 'M', 24),
  ((select id from retail_products where slug = 'printed-palazzo-suit-set'), 'L', 1),
  ((select id from retail_products where slug = 'printed-palazzo-suit-set'), 'XL', 0),
  ((select id from retail_products where slug = 'printed-maxi-dress'), 'S', 4),
  ((select id from retail_products where slug = 'printed-maxi-dress'), 'M', 3),
  ((select id from retail_products where slug = 'printed-maxi-dress'), 'L', 19),
  ((select id from retail_products where slug = 'printed-maxi-dress'), 'XL', 0),
  ((select id from retail_products where slug = 'floral-wrap-dress'), 'S', 31),
  ((select id from retail_products where slug = 'floral-wrap-dress'), 'M', 25),
  ((select id from retail_products where slug = 'floral-wrap-dress'), 'L', 24),
  ((select id from retail_products where slug = 'floral-wrap-dress'), 'XL', 0),
  ((select id from retail_products where slug = 'denim-shirt-dress'), 'S', 1),
  ((select id from retail_products where slug = 'denim-shirt-dress'), 'M', 4),
  ((select id from retail_products where slug = 'denim-shirt-dress'), 'L', 25),
  ((select id from retail_products where slug = 'denim-shirt-dress'), 'XL', 0),
  ((select id from retail_products where slug = 'ruffle-sleeve-top'), 'S', 13),
  ((select id from retail_products where slug = 'ruffle-sleeve-top'), 'M', 27),
  ((select id from retail_products where slug = 'ruffle-sleeve-top'), 'L', 4),
  ((select id from retail_products where slug = 'ruffle-sleeve-top'), 'XL', 0),
  ((select id from retail_products where slug = 'satin-cami-top'), 'S', 25),
  ((select id from retail_products where slug = 'satin-cami-top'), 'M', 19),
  ((select id from retail_products where slug = 'satin-cami-top'), 'L', 18),
  ((select id from retail_products where slug = 'satin-cami-top'), 'XL', 0),
  ((select id from retail_products where slug = 'high-rise-straight-jeans'), '28', 21),
  ((select id from retail_products where slug = 'high-rise-straight-jeans'), '30', 14),
  ((select id from retail_products where slug = 'high-rise-straight-jeans'), '32', 4),
  ((select id from retail_products where slug = 'high-rise-straight-jeans'), '34', 18),
  ((select id from retail_products where slug = 'skinny-fit-ankle-jeans'), '28', 29),
  ((select id from retail_products where slug = 'skinny-fit-ankle-jeans'), '30', 22),
  ((select id from retail_products where slug = 'skinny-fit-ankle-jeans'), '32', 2),
  ((select id from retail_products where slug = 'skinny-fit-ankle-jeans'), '34', 26),
  ((select id from retail_products where slug = 'womens-quilted-puffer-jacket'), 'S', 27),
  ((select id from retail_products where slug = 'womens-quilted-puffer-jacket'), 'M', 21),
  ((select id from retail_products where slug = 'womens-quilted-puffer-jacket'), 'L', 3),
  ((select id from retail_products where slug = 'womens-quilted-puffer-jacket'), 'XL', 0),
  ((select id from retail_products where slug = 'graphic-print-oversized-tee'), 'S', 19),
  ((select id from retail_products where slug = 'graphic-print-oversized-tee'), 'M', 13),
  ((select id from retail_products where slug = 'graphic-print-oversized-tee'), 'L', 1),
  ((select id from retail_products where slug = 'graphic-print-oversized-tee'), 'XL', 0),
  ((select id from retail_products where slug = 'classic-crew-neck-tee'), 'S', 28),
  ((select id from retail_products where slug = 'classic-crew-neck-tee'), 'M', 22),
  ((select id from retail_products where slug = 'classic-crew-neck-tee'), 'L', 21),
  ((select id from retail_products where slug = 'classic-crew-neck-tee'), 'XL', 0),
  ((select id from retail_products where slug = 'striped-polo-tshirt'), 'S', 2),
  ((select id from retail_products where slug = 'striped-polo-tshirt'), 'M', 1),
  ((select id from retail_products where slug = 'striped-polo-tshirt'), 'L', 22),
  ((select id from retail_products where slug = 'striped-polo-tshirt'), 'XL', 0),
  ((select id from retail_products where slug = 'classic-fit-formal-shirt'), 'S', 20),
  ((select id from retail_products where slug = 'classic-fit-formal-shirt'), 'M', 14),
  ((select id from retail_products where slug = 'classic-fit-formal-shirt'), 'L', 13),
  ((select id from retail_products where slug = 'classic-fit-formal-shirt'), 'XL', 0),
  ((select id from retail_products where slug = 'checked-casual-shirt'), 'S', 30),
  ((select id from retail_products where slug = 'checked-casual-shirt'), 'M', 24),
  ((select id from retail_products where slug = 'checked-casual-shirt'), 'L', 1),
  ((select id from retail_products where slug = 'checked-casual-shirt'), 'XL', 0),
  ((select id from retail_products where slug = 'mens-slim-fit-jeans'), '28', 14),
  ((select id from retail_products where slug = 'mens-slim-fit-jeans'), '30', 1),
  ((select id from retail_products where slug = 'mens-slim-fit-jeans'), '32', 29),
  ((select id from retail_products where slug = 'mens-slim-fit-jeans'), '34', 31),
  ((select id from retail_products where slug = 'slim-fit-chino-trousers'), '28', 24),
  ((select id from retail_products where slug = 'slim-fit-chino-trousers'), '30', 17),
  ((select id from retail_products where slug = 'slim-fit-chino-trousers'), '32', 2),
  ((select id from retail_products where slug = 'slim-fit-chino-trousers'), '34', 21),
  ((select id from retail_products where slug = 'formal-pleated-trousers'), '28', 15),
  ((select id from retail_products where slug = 'formal-pleated-trousers'), '30', 28),
  ((select id from retail_products where slug = 'formal-pleated-trousers'), '32', 3),
  ((select id from retail_products where slug = 'formal-pleated-trousers'), '34', 12),
  ((select id from retail_products where slug = 'nehru-jacket-set'), 'S', 22),
  ((select id from retail_products where slug = 'nehru-jacket-set'), 'M', 16),
  ((select id from retail_products where slug = 'nehru-jacket-set'), 'L', 3),
  ((select id from retail_products where slug = 'nehru-jacket-set'), 'XL', 0),
  ((select id from retail_products where slug = 'quilted-bomber-jacket'), 'S', 25),
  ((select id from retail_products where slug = 'quilted-bomber-jacket'), 'M', 19),
  ((select id from retail_products where slug = 'quilted-bomber-jacket'), 'L', 18),
  ((select id from retail_products where slug = 'quilted-bomber-jacket'), 'XL', 0),
  ((select id from retail_products where slug = 'mens-denim-jacket'), 'S', 13),
  ((select id from retail_products where slug = 'mens-denim-jacket'), 'M', 27),
  ((select id from retail_products where slug = 'mens-denim-jacket'), 'L', 4),
  ((select id from retail_products where slug = 'mens-denim-jacket'), 'XL', 0),
  ((select id from retail_products where slug = 'unicorn-print-frock'), '2-3Y', 15),
  ((select id from retail_products where slug = 'unicorn-print-frock'), '4-5Y', 19),
  ((select id from retail_products where slug = 'unicorn-print-frock'), '6-7Y', 1),
  ((select id from retail_products where slug = 'unicorn-print-frock'), '8-9Y', 0),
  ((select id from retail_products where slug = 'floral-cotton-frock'), '2-3Y', 26),
  ((select id from retail_products where slug = 'floral-cotton-frock'), '4-5Y', 30),
  ((select id from retail_products where slug = 'floral-cotton-frock'), '6-7Y', 2),
  ((select id from retail_products where slug = 'floral-cotton-frock'), '8-9Y', 0),
  ((select id from retail_products where slug = 'girls-lehenga-choli-set'), '2-3Y', 18),
  ((select id from retail_products where slug = 'girls-lehenga-choli-set'), '4-5Y', 1),
  ((select id from retail_products where slug = 'girls-lehenga-choli-set'), '6-7Y', 26),
  ((select id from retail_products where slug = 'girls-lehenga-choli-set'), '8-9Y', 0),
  ((select id from retail_products where slug = 'boys-printed-tshirt'), '2-3Y', 2),
  ((select id from retail_products where slug = 'boys-printed-tshirt'), '4-5Y', 23),
  ((select id from retail_products where slug = 'boys-printed-tshirt'), '6-7Y', 27),
  ((select id from retail_products where slug = 'boys-printed-tshirt'), '8-9Y', 0),
  ((select id from retail_products where slug = 'boys-solid-polo'), '2-3Y', 20),
  ((select id from retail_products where slug = 'boys-solid-polo'), '4-5Y', 24),
  ((select id from retail_products where slug = 'boys-solid-polo'), '6-7Y', 1),
  ((select id from retail_products where slug = 'boys-solid-polo'), '8-9Y', 0),
  ((select id from retail_products where slug = 'dino-print-tee-shorts-set'), '2-3Y', 16),
  ((select id from retail_products where slug = 'dino-print-tee-shorts-set'), '4-5Y', 3),
  ((select id from retail_products where slug = 'dino-print-tee-shorts-set'), '6-7Y', 24),
  ((select id from retail_products where slug = 'dino-print-tee-shorts-set'), '8-9Y', 0),
  ((select id from retail_products where slug = 'girls-floral-coord-set'), '2-3Y', 21),
  ((select id from retail_products where slug = 'girls-floral-coord-set'), '4-5Y', 3),
  ((select id from retail_products where slug = 'girls-floral-coord-set'), '6-7Y', 29),
  ((select id from retail_products where slug = 'girls-floral-coord-set'), '8-9Y', 0)
on conflict (product_id, label) do update set stock_qty = excluded.stock_qty;

-- ---------------------------------------------------------------------------
-- Wholesale catalogue (25 products)
-- ---------------------------------------------------------------------------

insert into wholesale_products (sku, slug, name, category, subcategory, description, images,
                               currency, moq, pack_size, size_run, fabric, colors,
                               lead_time_days, tags) values
  ('GV-WCT-001', 'cotton-round-neck-tee-bulk', 'Cotton Round Neck T-Shirt (Bulk Pack)', 'unisex'::wholesale_category,
   'Basics', '180 GSM combed cotton round neck tee, solid colours, sold in size-run packs ready for retail floor.',
   array['/placeholders/bulk-tee-pack-1d4ed8.svg']::text[],
   'INR', 120, 12, 'S-M-L-XL (2:4:4:2 ratio per pack of 12)', '180 GSM Combed Cotton',
   array['White', 'Black', 'Navy', 'Grey Melange']::text[], 7, array['bestseller']::wholesale_tag[]),
  ('GV-WHD-009', 'fleece-hoodie-bulk', 'Fleece Pullover Hoodie (Bulk Pack)', 'unisex'::wholesale_category,
   'Basics', '320 GSM brushed fleece pullover hoodie with kangaroo pocket, winter-season staple.',
   array['/placeholders/hoodie-bulk-374151.svg']::text[],
   'INR', 96, 8, 'S-M-L-XL (2:3:2:1 ratio per pack of 8)', '320 GSM Brushed Fleece',
   array['Black', 'Charcoal', 'Olive', 'Maroon']::text[], 15, array['new']::wholesale_tag[]),
  ('GV-WVN-010', 'cotton-vest-bulk', 'Cotton Ribbed Vest (Bulk Pack)', 'unisex'::wholesale_category,
   'Basics', 'Ribbed cotton innerwear vests, high-turnover everyday essential for general stores.',
   array['/placeholders/vest-bulk-e5e7eb.svg']::text[],
   'INR', 240, 24, 'S-M-L-XL (2:4:4:2 ratio per pack of 24)', '100% Combed Cotton Rib',
   array['White']::text[], 6, '{}'::wholesale_tag[]),
  ('GV-WAT-008', 'activewear-joggers-bulk', 'Activewear Joggers (Bulk Pack)', 'unisex'::wholesale_category,
   'Activewear', '4-way stretch jogger pants for activewear resale, moisture-wicking fabric.',
   array['/placeholders/joggers-bulk-0f172a.svg']::text[],
   'INR', 120, 12, 'S-M-L-XL (2:4:4:2 ratio per pack of 12)', '4-Way Stretch Polyester Blend',
   array['Black', 'Grey', 'Navy']::text[], 9, array['closeout']::wholesale_tag[]),
  ('GV-WDF-011', 'dryfit-sports-tee-bulk', 'Dry-Fit Sports T-Shirt (Bulk Pack)', 'unisex'::wholesale_category,
   'Activewear', 'Moisture-wicking polyester sports tee, popular for gyms, teams and event merchandise.',
   array['/placeholders/dry-fit-tee-bulk-0891b2.svg']::text[],
   'INR', 120, 12, 'S-M-L-XL (2:4:4:2 ratio per pack of 12)', '100% Micro Polyester, Dry-Fit',
   array['Royal Blue', 'Black', 'Red', 'Neon Green']::text[], 8, array['bestseller']::wholesale_tag[]),
  ('GV-WET-007', 'festive-ethnic-set-bulk', 'Festive Ethnic Kurta Set (Bulk Pack)', 'unisex'::wholesale_category,
   'Basics', 'Season-ready festive kurta sets, popular for Diwali and wedding-season retail stocking.',
   array['/placeholders/festive-ethnic-bulk-7c2d12.svg']::text[],
   'INR', 48, 6, 'S-M-L-XL (1:2:2:1 ratio per pack of 6)', 'Silk Blend',
   array['Maroon', 'Gold', 'Emerald']::text[], 21, array['new']::wholesale_tag[]),
  ('GV-WKR-002', 'cotton-printed-kurti-bulk', 'Cotton Printed Kurti (Bulk Pack)', 'women'::wholesale_category,
   'Kurtis', 'Rayon-cotton printed kurtis in fast-selling prints, curated seasonally for retail resale.',
   array['/placeholders/kurti-bulk-pack-be185d.svg']::text[],
   'INR', 60, 6, 'S-M-L-XL (1:2:2:1 ratio per pack of 6)', 'Rayon Cotton',
   array['Assorted seasonal prints']::text[], 10, array['new']::wholesale_tag[]),
  ('GV-WCK-012', 'chikankari-kurti-bulk', 'Chikankari Embroidered Kurti (Bulk Pack)', 'women'::wholesale_category,
   'Kurtis', 'Lucknowi chikankari embroidered kurtis on soft cotton, a year-round staple line.',
   array['/placeholders/chikankari-kurti-bulk-0e7490.svg']::text[],
   'INR', 60, 6, 'S-M-L-XL (1:2:2:1 ratio per pack of 6)', 'Cotton with hand embroidery',
   array['White', 'Powder Blue', 'Pastel Pink']::text[], 18, '{}'::wholesale_tag[]),
  ('GV-WAK-013', 'anarkali-kurta-bulk', 'Anarkali Flared Kurta (Bulk Pack)', 'women'::wholesale_category,
   'Kurtis', 'Floor-length flared anarkali kurtas in printed cotton-blend, festive-season mover.',
   array['/placeholders/anarkali-bulk-be123c.svg']::text[],
   'INR', 48, 6, 'S-M-L-XL (1:2:2:1 ratio per pack of 6)', 'Cotton Blend',
   array['Assorted festive prints']::text[], 16, '{}'::wholesale_tag[]),
  ('GV-WSS-014', 'printed-saree-bulk', 'Printed Georgette Saree (Bulk Pack)', 'women'::wholesale_category,
   'Sarees & Suit Sets', 'Lightweight georgette sarees with matching blouse pieces, packed by print family.',
   array['/placeholders/saree-bulk-a21caf.svg']::text[],
   'INR', 50, 10, 'Free size (blouse piece included)', 'Georgette',
   array['Assorted prints']::text[], 14, array['bestseller']::wholesale_tag[]),
  ('GV-WSU-015', 'unstitched-suit-set-bulk', 'Unstitched 3-Piece Suit Set (Bulk Pack)', 'women'::wholesale_category,
   'Sarees & Suit Sets', 'Unstitched cotton suit sets — top, bottom and dupatta — a reliable volume category.',
   array['/placeholders/suit-set-bulk-0d9488.svg']::text[],
   'INR', 60, 10, 'Unstitched (2.5m top / 2.5m bottom / 2.25m dupatta)', 'Cotton',
   array['Assorted prints']::text[], 12, '{}'::wholesale_tag[]),
  ('GV-WWT-016', 'womens-rayon-top-bulk', 'Women''s Rayon Top (Bulk Pack)', 'women'::wholesale_category,
   'Western Wear', 'Casual rayon tops in seasonal cuts and prints, fast-turnover western category.',
   array['/placeholders/rayon-top-bulk-db2777.svg']::text[],
   'INR', 72, 12, 'S-M-L-XL (2:4:4:2 ratio per pack of 12)', 'Rayon',
   array['Assorted prints']::text[], 10, '{}'::wholesale_tag[]),
  ('GV-WPO-017', 'mens-pique-polo-bulk', 'Men''s Pique Polo T-Shirt (Bulk Pack)', 'men'::wholesale_category,
   'T-Shirts & Polos', 'Classic pique cotton polos with ribbed collar, a corporate-gifting and retail staple.',
   array['/placeholders/polo-bulk-166534.svg']::text[],
   'INR', 120, 12, 'S-M-L-XL (2:4:4:2 ratio per pack of 12)', '220 GSM Cotton Pique',
   array['Navy', 'White', 'Bottle Green', 'Maroon']::text[], 9, array['bestseller']::wholesale_tag[]),
  ('GV-WFR-006', 'formal-shirt-bulk', 'Formal Cotton Shirt (Bulk Pack)', 'men'::wholesale_category,
   'Shirts', 'Non-iron finish formal shirts in classic office colourways, retail-ready tagging included.',
   array['/placeholders/formal-shirt-bulk-334155.svg']::text[],
   'INR', 96, 8, 'S-M-L-XL (2:3:2:1 ratio per pack of 8)', 'Cotton Poly Blend, Non-Iron Finish',
   array['White', 'Sky Blue', 'Charcoal']::text[], 12, '{}'::wholesale_tag[]),
  ('GV-WCS-018', 'casual-checked-shirt-bulk', 'Casual Checked Shirt (Bulk Pack)', 'men'::wholesale_category,
   'Shirts', 'Brushed-cotton checked casual shirts, assorted check patterns per carton.',
   array['/placeholders/checked-shirt-bulk-7f1d1d.svg']::text[],
   'INR', 96, 8, 'S-M-L-XL (2:3:2:1 ratio per pack of 8)', 'Brushed Cotton',
   array['Assorted checks']::text[], 12, '{}'::wholesale_tag[]),
  ('GV-WDN-003', 'denim-jeans-bulk', 'Stretch Denim Jeans (Bulk Pack)', 'men'::wholesale_category,
   'Denim & Trousers', '5-pocket stretch denim jeans in wash-finished indigo and black, factory-packed.',
   array['/placeholders/denim-bulk-pack-1e40af.svg']::text[],
   'INR', 96, 8, '30-32-34-36 (2:3:2:1 ratio per pack of 8)', '98% Cotton / 2% Spandex',
   array['Indigo Wash', 'Black Wash']::text[], 14, '{}'::wholesale_tag[]),
  ('GV-WCH-019', 'cotton-chino-trouser-bulk', 'Cotton Chino Trousers (Bulk Pack)', 'men'::wholesale_category,
   'Denim & Trousers', 'Flat-front cotton chinos in core colours, smart-casual line for menswear retail.',
   array['/placeholders/chino-bulk-78350f.svg']::text[],
   'INR', 96, 8, '30-32-34-36 (2:3:2:1 ratio per pack of 8)', 'Cotton Twill',
   array['Khaki', 'Navy', 'Black', 'Stone']::text[], 13, '{}'::wholesale_tag[]),
  ('GV-WMK-020', 'mens-cotton-kurta-bulk', 'Men''s Cotton Kurta (Bulk Pack)', 'men'::wholesale_category,
   'Ethnic Wear', 'Straight-cut cotton kurtas in solid colours, steady festive and everyday ethnic demand.',
   array['/placeholders/mens-kurta-bulk-065f46.svg']::text[],
   'INR', 60, 6, 'S-M-L-XL (1:2:2:1 ratio per pack of 6)', 'Cotton',
   array['White', 'Cream', 'Beige', 'Sage']::text[], 14, '{}'::wholesale_tag[]),
  ('GV-WKD-004', 'kids-cotton-coord-set-bulk', 'Kids Cotton Co-ord Set (Bulk Pack)', 'kids'::wholesale_category,
   'Co-ord Sets', 'Everyday cotton tee-and-shorts co-ord sets for kids, mixed prints per carton.',
   array['/placeholders/kids-co-ord-bulk-16a34a.svg']::text[],
   'INR', 72, 12, '2-3Y to 8-9Y (mixed ratio per pack of 12)', 'Cotton Blend',
   array['Assorted']::text[], 10, array['bestseller']::wholesale_tag[]),
  ('GV-WKT-021', 'kids-printed-tee-bulk', 'Kids Printed T-Shirt (Bulk Pack)', 'kids'::wholesale_category,
   'T-Shirts & Dresses', 'Cotton kids tees with cartoon and slogan prints, high-rotation everyday category.',
   array['/placeholders/kids-tee-bulk-0369a1.svg']::text[],
   'INR', 96, 12, '2-3Y to 8-9Y (mixed ratio per pack of 12)', 'Cotton Single Jersey',
   array['Assorted prints']::text[], 8, '{}'::wholesale_tag[]),
  ('GV-WKF-022', 'kids-cotton-frock-bulk', 'Kids Cotton Frock (Bulk Pack)', 'kids'::wholesale_category,
   'T-Shirts & Dresses', 'Printed cotton frocks for girls, assorted florals and seasonal prints per pack.',
   array['/placeholders/kids-frock-bulk-c026d3.svg']::text[],
   'INR', 72, 12, '2-3Y to 8-9Y (mixed ratio per pack of 12)', 'Cotton',
   array['Assorted prints']::text[], 11, array['new']::wholesale_tag[]),
  ('GV-WCF-023', 'cotton-poplin-fabric-bulk', 'Cotton Poplin Fabric (Bulk Roll)', 'fabric'::wholesale_category,
   'Cotton Fabric', 'Mill-finished cotton poplin, sold by the metre for shirting and uniform manufacturing.',
   array['/placeholders/poplin-fabric-0284c7.svg']::text[],
   'INR', 300, 50, 'N/A — sold by the metre (58in width)', '100% Cotton Poplin',
   array['White', 'Sky Blue', 'Dyed to order']::text[], 16, '{}'::wholesale_tag[]),
  ('GV-WDF-024', 'denim-fabric-bulk', 'Denim Fabric (Bulk Roll)', 'fabric'::wholesale_category,
   'Cotton Fabric', '10 oz indigo denim fabric by the metre, for jeans and jacket manufacturing.',
   array['/placeholders/denim-fabric-1e3a8a.svg']::text[],
   'INR', 300, 50, 'N/A — sold by the metre (60in width)', '10 oz Cotton Denim',
   array['Indigo', 'Black']::text[], 20, '{}'::wholesale_tag[]),
  ('GV-WSR-005', 'chikankari-kurti-fabric-bulk', 'Chikankari Embroidered Fabric (Bulk Roll)', 'fabric'::wholesale_category,
   'Embroidered & Silk Blend', 'Lucknowi chikankari hand-embroidered cotton fabric, sold by the roll for manufacturing.',
   array['/placeholders/chikankari-fabric-0e7490.svg']::text[],
   'INR', 200, 50, 'N/A — sold by the metre', '100% Cotton, hand embroidery',
   array['White base', 'Pastel base']::text[], 18, '{}'::wholesale_tag[]),
  ('GV-WSF-025', 'banarasi-silk-blend-fabric-bulk', 'Banarasi Silk Blend Fabric (Bulk Roll)', 'fabric'::wholesale_category,
   'Embroidered & Silk Blend', 'Zari-woven silk blend fabric for festive and bridal-wear manufacturing, sold by the metre.',
   array['/placeholders/silk-blend-fabric-9d174d.svg']::text[],
   'INR', 150, 25, 'N/A — sold by the metre (44in width)', 'Silk Blend with zari weave',
   array['Maroon', 'Emerald', 'Royal Blue', 'Gold']::text[], 24, array['new']::wholesale_tag[])
on conflict (slug) do update set
  sku = excluded.sku,
  name = excluded.name,
  category = excluded.category,
  subcategory = excluded.subcategory,
  description = excluded.description,
  images = excluded.images,
  moq = excluded.moq,
  pack_size = excluded.pack_size,
  size_run = excluded.size_run,
  fabric = excluded.fabric,
  colors = excluded.colors,
  lead_time_days = excluded.lead_time_days,
  tags = excluded.tags,
  is_active = true;

-- Quantity-break pricing.

insert into wholesale_price_tiers (product_id, min_qty, price_per_unit) values
  ((select id from wholesale_products where slug = 'cotton-round-neck-tee-bulk'), 120, 24900),
  ((select id from wholesale_products where slug = 'cotton-round-neck-tee-bulk'), 300, 21900),
  ((select id from wholesale_products where slug = 'cotton-round-neck-tee-bulk'), 600, 18900),
  ((select id from wholesale_products where slug = 'fleece-hoodie-bulk'), 96, 59900),
  ((select id from wholesale_products where slug = 'fleece-hoodie-bulk'), 240, 52900),
  ((select id from wholesale_products where slug = 'fleece-hoodie-bulk'), 480, 45900),
  ((select id from wholesale_products where slug = 'cotton-vest-bulk'), 240, 9900),
  ((select id from wholesale_products where slug = 'cotton-vest-bulk'), 600, 8400),
  ((select id from wholesale_products where slug = 'cotton-vest-bulk'), 1200, 6900),
  ((select id from wholesale_products where slug = 'activewear-joggers-bulk'), 120, 34900),
  ((select id from wholesale_products where slug = 'activewear-joggers-bulk'), 300, 29900),
  ((select id from wholesale_products where slug = 'activewear-joggers-bulk'), 600, 25900),
  ((select id from wholesale_products where slug = 'dryfit-sports-tee-bulk'), 120, 21900),
  ((select id from wholesale_products where slug = 'dryfit-sports-tee-bulk'), 300, 18900),
  ((select id from wholesale_products where slug = 'dryfit-sports-tee-bulk'), 600, 15900),
  ((select id from wholesale_products where slug = 'festive-ethnic-set-bulk'), 48, 79900),
  ((select id from wholesale_products where slug = 'festive-ethnic-set-bulk'), 120, 69900),
  ((select id from wholesale_products where slug = 'festive-ethnic-set-bulk'), 240, 59900),
  ((select id from wholesale_products where slug = 'cotton-printed-kurti-bulk'), 60, 39900),
  ((select id from wholesale_products where slug = 'cotton-printed-kurti-bulk'), 150, 34900),
  ((select id from wholesale_products where slug = 'cotton-printed-kurti-bulk'), 300, 29900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-bulk'), 60, 54900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-bulk'), 150, 48900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-bulk'), 300, 42900),
  ((select id from wholesale_products where slug = 'anarkali-kurta-bulk'), 48, 64900),
  ((select id from wholesale_products where slug = 'anarkali-kurta-bulk'), 120, 57900),
  ((select id from wholesale_products where slug = 'anarkali-kurta-bulk'), 240, 49900),
  ((select id from wholesale_products where slug = 'printed-saree-bulk'), 50, 59900),
  ((select id from wholesale_products where slug = 'printed-saree-bulk'), 150, 52900),
  ((select id from wholesale_products where slug = 'printed-saree-bulk'), 300, 44900),
  ((select id from wholesale_products where slug = 'unstitched-suit-set-bulk'), 60, 47900),
  ((select id from wholesale_products where slug = 'unstitched-suit-set-bulk'), 180, 41900),
  ((select id from wholesale_products where slug = 'unstitched-suit-set-bulk'), 360, 35900),
  ((select id from wholesale_products where slug = 'womens-rayon-top-bulk'), 72, 26900),
  ((select id from wholesale_products where slug = 'womens-rayon-top-bulk'), 180, 22900),
  ((select id from wholesale_products where slug = 'womens-rayon-top-bulk'), 360, 18900),
  ((select id from wholesale_products where slug = 'mens-pique-polo-bulk'), 120, 32900),
  ((select id from wholesale_products where slug = 'mens-pique-polo-bulk'), 300, 28900),
  ((select id from wholesale_products where slug = 'mens-pique-polo-bulk'), 600, 24900),
  ((select id from wholesale_products where slug = 'formal-shirt-bulk'), 96, 44900),
  ((select id from wholesale_products where slug = 'formal-shirt-bulk'), 240, 39900),
  ((select id from wholesale_products where slug = 'formal-shirt-bulk'), 480, 34900),
  ((select id from wholesale_products where slug = 'casual-checked-shirt-bulk'), 96, 38900),
  ((select id from wholesale_products where slug = 'casual-checked-shirt-bulk'), 240, 33900),
  ((select id from wholesale_products where slug = 'casual-checked-shirt-bulk'), 480, 28900),
  ((select id from wholesale_products where slug = 'denim-jeans-bulk'), 96, 64900),
  ((select id from wholesale_products where slug = 'denim-jeans-bulk'), 240, 57900),
  ((select id from wholesale_products where slug = 'denim-jeans-bulk'), 480, 49900),
  ((select id from wholesale_products where slug = 'cotton-chino-trouser-bulk'), 96, 52900),
  ((select id from wholesale_products where slug = 'cotton-chino-trouser-bulk'), 240, 46900),
  ((select id from wholesale_products where slug = 'cotton-chino-trouser-bulk'), 480, 39900),
  ((select id from wholesale_products where slug = 'mens-cotton-kurta-bulk'), 60, 44900),
  ((select id from wholesale_products where slug = 'mens-cotton-kurta-bulk'), 150, 39900),
  ((select id from wholesale_products where slug = 'mens-cotton-kurta-bulk'), 300, 33900),
  ((select id from wholesale_products where slug = 'kids-cotton-coord-set-bulk'), 72, 18900),
  ((select id from wholesale_products where slug = 'kids-cotton-coord-set-bulk'), 180, 16400),
  ((select id from wholesale_products where slug = 'kids-cotton-coord-set-bulk'), 360, 13900),
  ((select id from wholesale_products where slug = 'kids-printed-tee-bulk'), 96, 12900),
  ((select id from wholesale_products where slug = 'kids-printed-tee-bulk'), 240, 10900),
  ((select id from wholesale_products where slug = 'kids-printed-tee-bulk'), 480, 8900),
  ((select id from wholesale_products where slug = 'kids-cotton-frock-bulk'), 72, 22900),
  ((select id from wholesale_products where slug = 'kids-cotton-frock-bulk'), 180, 19400),
  ((select id from wholesale_products where slug = 'kids-cotton-frock-bulk'), 360, 16400),
  ((select id from wholesale_products where slug = 'cotton-poplin-fabric-bulk'), 300, 14900),
  ((select id from wholesale_products where slug = 'cotton-poplin-fabric-bulk'), 900, 12900),
  ((select id from wholesale_products where slug = 'cotton-poplin-fabric-bulk'), 1800, 10900),
  ((select id from wholesale_products where slug = 'denim-fabric-bulk'), 300, 26900),
  ((select id from wholesale_products where slug = 'denim-fabric-bulk'), 900, 23900),
  ((select id from wholesale_products where slug = 'denim-fabric-bulk'), 1800, 19900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-fabric-bulk'), 200, 8900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-fabric-bulk'), 500, 7900),
  ((select id from wholesale_products where slug = 'chikankari-kurti-fabric-bulk'), 1000, 6900),
  ((select id from wholesale_products where slug = 'banarasi-silk-blend-fabric-bulk'), 150, 42900),
  ((select id from wholesale_products where slug = 'banarasi-silk-blend-fabric-bulk'), 450, 37900),
  ((select id from wholesale_products where slug = 'banarasi-silk-blend-fabric-bulk'), 900, 32900)
on conflict (product_id, min_qty) do update set price_per_unit = excluded.price_per_unit;
