// Shared money type: prices are stored in minor units (paise for INR, cents for USD)
// to avoid floating point issues, formatted with formatPrice() from lib/utils.

export type Currency = "INR" | "USD";

// ---------------------------------------------------------------------------
// Retail catalog — individual shoppers, single-unit purchases (Myntra-style)
// ---------------------------------------------------------------------------

export type RetailCategory = "women" | "men" | "kids";

/**
 * The badges a product can carry.
 *
 * Named so the database mapping can filter against it — `retail_products.tags`
 * is a Postgres enum array, and the two lists are free to drift, so an unknown
 * value has to be dropped rather than rendered as a badge nobody styled.
 */
export type RetailTag = "new" | "bestseller" | "sale";

export interface RetailSize {
  label: string; // e.g. "S", "M", "L", "XL", "32", "34"
  inStock: boolean;
  /**
   * Units on the shelf, when the catalogue came from the database.
   *
   * Undefined when it came from src/lib/mock/, which only carries the
   * `inStock` boolean — see the fallback note in lib/catalogue/retail.ts. That
   * is what the optionality means: not "stock is unknown" but "this deployment
   * has no database to know it", which `getStock()` answers with the same
   * deterministic seed the module has always used.
   *
   * Where it IS defined it is authoritative, because it is the number
   * `place_retail_order` decrements and refuses orders against. Anything that
   * decides whether a size can be bought must read this rather than a browser's
   * own idea of it.
   */
  stock?: number;
}

export interface RetailProduct {
  /**
   * The app's product identity, which is the slug.
   *
   * Not the database's. `retail_products.id` is a uuid generated by Postgres,
   * different in every environment because the seed does not set it — so a
   * wishlist, a review or a stock override keyed on one would orphan the next
   * time a database was created. Nine localStorage stores key on this field.
   *
   * The slug is the only identifier both sides share, which is why
   * `place_retail_order`, `cart_add` and `active_product_id` all address
   * products by it and keep the uuid server-side. This makes the storefront
   * agree: whether a product comes from src/lib/mock/ or from the database,
   * `id` is the same string, and the uuid never leaves the data layer.
   *
   * Kept as a distinct field rather than deleting it in favour of `slug`
   * because 219 call sites read it, and a rename of that size is risk with no
   * behaviour attached. `scripts/qa/static-checks.mjs` asserts the two match
   * so they cannot drift apart.
   */
  id: string;
  slug: string;
  name: string;
  brand: string;
  category: RetailCategory;
  subcategory: string; // e.g. "Kurtas", "T-Shirts", "Sarees"
  description: string;
  images: string[]; // color-coded placeholder swatches for now
  price: number; // minor units, current selling price
  mrp: number; // minor units, original price (for strike-through)
  currency: Currency;
  sizes: RetailSize[];
  colors: string[];
  rating: number; // 0-5
  ratingCount: number;
  tags?: RetailTag[];
}

// ---------------------------------------------------------------------------
// Wholesale catalog — B2B buyers, bulk purchases with MOQ + tiered pricing
// ---------------------------------------------------------------------------

export type WholesaleCategory = "women" | "men" | "kids" | "unisex" | "fabric";

/** The badges a wholesale product can carry. See RetailTag for why it is named. */
export type WholesaleTag = "new" | "bestseller" | "closeout";

export interface WholesalePriceTier {
  minQty: number; // minimum units to unlock this price
  pricePerUnit: number; // minor units, per single garment unit
}

export interface WholesaleProduct {
  /** The slug, for the same reasons as RetailProduct.id — see the note there. */
  id: string;
  sku: string;
  slug: string;
  name: string;
  category: WholesaleCategory;
  subcategory: string; // e.g. "T-Shirts & Polos", "Denim & Trousers"
  description: string;
  images: string[];
  currency: Currency;
  moq: number; // minimum order quantity, in units
  packSize: number; // units per pack/carton (orders are placed in multiples of this)
  priceTiers: WholesalePriceTier[]; // sorted ascending by minQty
  sizeRun: string; // e.g. "S-M-L-XL (2:4:4:2 ratio per pack)"
  fabric: string;
  colors: string[];
  leadTimeDays: number;
  tags?: WholesaleTag[];
}

export function wholesalePriceForQty(product: WholesaleProduct, qty: number): number {
  let price = product.priceTiers[0]?.pricePerUnit ?? 0;
  for (const tier of product.priceTiers) {
    if (qty >= tier.minQty) price = tier.pricePerUnit;
  }
  return price;
}
